version: '3.7'

services:
  eventstore.db:
    image: docker.pkg.github.com/eventstore/eventstore/eventstore:ci
    environment:
      - EVENTSTORE_DEV=true
      - EVENTSTORE_RUN_PROJECTIONS=all
    ports:
      - "1113:1113"
      - "2113:2113"